[package]
name = "ptrace_future"
version = "0.1.0"
authors = ["gatowololo <gatowololo@gmail.com>"]
edition = "2018"

[dependencies]
futures-preview = "0.3.0-alpha.16"
nix = "0.14.0"
libc = "0.2"

[build-dependencies]
cc = "1.0"